### ISSUE TITLE
Error while running MobileNetV1

### ISSUE THREAD

**Issue by surya00060** [pulp-platform/pulp-sdk#126]
Hi!

I was trying to execute the MobileNetV1 application on GVSoC but it failed giving the following error. Any idea how to fix it? The tests were running fine! 

`Launching GVSOC with command:
gvsoc_launcher --config=gvsoc_config.json
Error FS mounting !
make: *** [/local/scratch/a/Tools/pulp-sdk/rtos/pulpos/common/rules/pulpos/default_rules.mk:327: run] Error 254
`

**Comment by NBruschi** [comment]
Thank you for reporting @surya00060. The MR #120 should fix the issue.

**Comment by surya00060** [comment]
Thanks for replying back! 
But unfortunately the latest commit doesn't fix the error. The error is still there.
Any idea why its failing?

**Comment by NBruschi** [comment]
Hi @surya00060! Thanks again for reporting. The latest commits should have finally solved the issue.
